// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLoginStatus(arg1) {
  return window['go']['main']['App']['CheckLoginStatus'](arg1);
}

export function GetLoginQRCode() {
  return window['go']['main']['App']['GetLoginQRCode']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function ResolveVideo(arg1) {
  return window['go']['main']['App']['ResolveVideo'](arg1);
}
