// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CheckLoginStatus(arg1:string):Promise<model.Response>;

export function GetLoginQRCode():Promise<model.Response>;

export function GetUserInfo():Promise<model.Response>;

export function ResolveVideo(arg1:string):Promise<model.Response>;
